# -*- mode: ruby -*-
# vim: set ft=ruby tabstop=2 expandtab:

Vagrant::Config.run do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  
  config.vm.provision :chef_solo do |chef|
    
    chef.cookbooks_path = ["../cookbooks", "../cookbooks-mantisbt"]

    chef.add_recipe "apt::default"
    chef.add_recipe "apache2"
    chef.add_recipe "postgresql"
    chef.add_recipe "postgresql::server"
    chef.add_recipe "git"
    chef.add_recipe "mantisbt"
    chef.add_recipe "php"
    chef.add_recipe "php::module_pgsql"
    chef.add_recipe "apache2::mod_php5"

    chef.json = { 
      :apache => { 
        :default_site_enabled => true 
      },
      :postgresql => {
        :listen_address => "localhost",
        :password => {
          "postgres" => "toor"
        }
      },
      :git => {
        :repository => "https://github.com/mantisbt/mantisbt.git",
        :reference => "master",
        :action => "checkout",
        :destination => "/home/vagrant/mantisbt"
      }
    }
    
  end

  config.vm.forward_port 80, 8888
  
end
